name = input("Please put your name here: ")
region = input("Please put the region you live at in here: ")
city = input("Please type your city: ")
index_city = int(input("Please type your index here: "))
phone = str(input("Please point your phone number: "))
edu_spec = input("Please point your education specialization: ")
print("Hello, ", name, ", it`s nice to see you!", "\nThe data you have pointed is: " "\nRegion: ", region, "\nCity: ", city, "\nIndex: ", index_city,"\nPhone number: ", phone, "\nEducation specialization: ", edu_spec)