lenght_row = float(input("Пожалуйста, введите длинну гляды: "))
supp_env = float(input("Введите пространство, занимаемое концевыми опорами в метрах: "))
vol_env = float(input("Введите пространство между концевыми опорами в метрах: "))
quant = (lenght_row-(2*(supp_env))/vol_env)
print("Вы можете высадить: ", int(quant), "кустов винограда")
