import turtle
turtle.pensize(14)
turtle.bgcolor('gray')
turtle.pencolor('blue')
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.left(180)
turtle.forward(400)
turtle.circle(20)
turtle.goto(-100,35)
turtle.write("Hello world!")
turtle.done()
